services:
  - type: web
    name: restaurantmenu
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn RestaurantMenu.wsgi:application
    plan: free
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: 'True'
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          name: restaurantmenu
          property: host
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
