# Generated by Django 4.2.7 on 2026-03-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_fooditem_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.restaurant'),
            preserve_default=False,
        ),
    ]
