# Generated by Django 4.2.7 on 2026-03-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_fooditem_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
