# Generated by Django 5.2.12 on 2026-03-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_restaurant_qr_code_restaurant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
