# Generated by Django 5.2.12 on 2026-03-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_restaurant_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_available',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
